### ISSUE TITLE
我自己写的注册怎么说我没定义，但是我又找不到在哪里

### ISSUE THREAD

**Issue by silverWolf818** [liadbiz/share#1]
Cannot read property 'name' of undefined

TypeError: Cannot read property 'name' of undefined
    at F:\blog\routes\signup.js:12:22

**Comment by liadbiz** [comment]
你的这个name是想获取表单中的name吗?  
1. 如果是指req.body.name 中的name. 可能是req对象没传进来
2. 然后, 如果你的组织是和我一样的话,  我猜可能是app对象没有传给router, 查看一下routes/index.js
3. 如果结构和我不一样, 麻烦贴一下signup.js......
@mirrorpal

**Comment by silverWolf818** [comment]
https://github.com/mirrorpal/mi 这是我的代码地址，是的应该是req没传过来， = =我直接复制你的signup.js 可能是我结构的原因我改了，我用了模板和你的稍微有点区别， = =我是一个新手有点不太懂

**Comment by liadbiz** [comment]
@mirrorpal  已经给你发了pr了.麻烦查看~~

**Comment by silverWolf818** [comment]
嗯，刚才在干活，可以运行了，对了你是怎么学习nodejs的，我完全没有头绪，新手一个才进入前端领域JS玩的也不是很6

**Comment by liadbiz** [comment]
@mirrorpal 
我也新手....学node也就才两个周...不过我觉得最好的方法就是去用node写点什么.然后搞清楚原理. 试着去实现一些已经有的东西. 一起加油~~~

**Comment by silverWolf818** [comment]
但是你能找到关键问题，有资料吗？其实好多我都看不懂= =例如signup.js我是复制你的，希望能看点基础的，一上来就直接写有点懵，我买了那个nodejs入门完全坑爹都是几年的，好多API都改了命令都是错的，你有什么好的资料吗?求推荐

**Comment by liadbiz** [comment]
这样啊...首先, 如果你的js基础不是很好, 建议你先去补一下js的基础. 然后, node的基础, 也就只是api了, 不过说实话, 看api真的是看不进去的, 而且现在node现在6.0都出来了,  追赶api是无底洞. 你之所以觉得懵, 我觉得可能是还是不太懂框架的是怎么一起工作的.....至于资料,
[js基础](http://www.liaoxuefeng.com/wiki/001434446689867b27157e896e74d51a89c25cc8b43bdb3000)
node
[node api](http://nodeapi.ucdok.com/#/api/)
然后若干网上推荐的经典书籍.自己取舍....

**Comment by silverWolf818** [comment]
JS的话，基础还是没问题毕竟也工作一年了，简单的原型封装继承Jquery插件还是可以应付，现在想提升一下自己，node好多ES6的语法require，import，model，export，包括之前了解的react，ng。不学点什么感觉太low了，公司又只有我一个人前端又不重视只能自己玩。看过react，vue，webpack，自动化都是基于node玩的，感觉先学好node很有必要。

**Comment by liadbiz** [comment]
只有一个前端...那你好寂寞啊...寂寞的男人(坏笑)
不够我觉得node只是个服务器端的js运行环境...熟悉环境的最好方法还是在这个环境里面做点事情....所以, 还是拿vue, react, ng什么的做个项目, 估计写完node就熟悉了....
对了你在哪儿工作啊(赤裸勾搭)

**Comment by silverWolf818** [comment]
帝都呢（坏笑），可能干完今年辞职，深造一下找个有前端团队的干，后端产品UI哎天天被攻击，烦各种改改改宝宝心里苦

**Comment by liadbiz** [comment]
现在先积累一点经验罗~在帝都也是不容易.加油思密达!
